[package]
name = "rusty-s3"
version = "0.1.0"
authors = ["Paolo Barbolini <paolo@paolo565.org>", "Federico Guerinoni <guerinoni.federico@gmail.com>"]
edition = "2018"

[dependencies]
hmac = "0.10.1"
sha2 = "0.9.2"
hex = "0.4"
time = { version = "0.2.23", default-features = true }
url = "2.2.0"
percent-encoding = "2.1.0"
form_urlencoded = "1.0.0"

[dev-dependencies]
pretty_assertions = "0.6.1"
